/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication2;

import java.awt.Color;

/**
 *
 * @author Hp
 */
public class pickghe extends javax.swing.JFrame {

    /**
     * Creates new form pickghe
     */
    public pickghe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        A8 = new javax.swing.JButton();
        A7 = new javax.swing.JButton();
        A6 = new javax.swing.JButton();
        A5 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton131 = new javax.swing.JButton();
        jButton132 = new javax.swing.JButton();
        jButton133 = new javax.swing.JButton();
        jButton134 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        A = new javax.swing.JLabel();
        B = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        A4 = new javax.swing.JButton();
        A3 = new javax.swing.JButton();
        A2 = new javax.swing.JButton();
        A1 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jButton65 = new javax.swing.JButton();
        jButton66 = new javax.swing.JButton();
        jButton67 = new javax.swing.JButton();
        jButton68 = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jButton70 = new javax.swing.JButton();
        jButton71 = new javax.swing.JButton();
        jButton72 = new javax.swing.JButton();
        jButton73 = new javax.swing.JButton();
        jButton74 = new javax.swing.JButton();
        jButton75 = new javax.swing.JButton();
        jButton76 = new javax.swing.JButton();
        jButton77 = new javax.swing.JButton();
        jButton78 = new javax.swing.JButton();
        jButton79 = new javax.swing.JButton();
        jButton80 = new javax.swing.JButton();
        jButton81 = new javax.swing.JButton();
        jButton82 = new javax.swing.JButton();
        jButton83 = new javax.swing.JButton();
        jButton84 = new javax.swing.JButton();
        jButton85 = new javax.swing.JButton();
        jButton86 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        A12 = new javax.swing.JButton();
        A11 = new javax.swing.JButton();
        A10 = new javax.swing.JButton();
        A9 = new javax.swing.JButton();
        B12 = new javax.swing.JButton();
        jButton92 = new javax.swing.JButton();
        jButton93 = new javax.swing.JButton();
        jButton94 = new javax.swing.JButton();
        C12 = new javax.swing.JButton();
        jButton96 = new javax.swing.JButton();
        jButton97 = new javax.swing.JButton();
        jButton98 = new javax.swing.JButton();
        D12 = new javax.swing.JButton();
        jButton100 = new javax.swing.JButton();
        jButton101 = new javax.swing.JButton();
        jButton102 = new javax.swing.JButton();
        E12 = new javax.swing.JButton();
        jButton104 = new javax.swing.JButton();
        jButton105 = new javax.swing.JButton();
        jButton106 = new javax.swing.JButton();
        F12 = new javax.swing.JButton();
        jButton108 = new javax.swing.JButton();
        jButton109 = new javax.swing.JButton();
        jButton110 = new javax.swing.JButton();
        G12 = new javax.swing.JButton();
        jButton112 = new javax.swing.JButton();
        jButton113 = new javax.swing.JButton();
        jButton114 = new javax.swing.JButton();
        jButton115 = new javax.swing.JButton();
        jButton116 = new javax.swing.JButton();
        jButton117 = new javax.swing.JButton();
        jButton118 = new javax.swing.JButton();
        jButton119 = new javax.swing.JButton();
        jButton120 = new javax.swing.JButton();
        jButton121 = new javax.swing.JButton();
        jButton122 = new javax.swing.JButton();
        jButton123 = new javax.swing.JButton();
        jButton124 = new javax.swing.JButton();
        jButton125 = new javax.swing.JButton();
        jButton126 = new javax.swing.JButton();
        jButton127 = new javax.swing.JButton();
        jButton128 = new javax.swing.JButton();
        jButton129 = new javax.swing.JButton();
        jButton130 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MÀN HÌNH");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 230, 50));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new java.awt.GridLayout(11, 4));

        A8.setBackground(new java.awt.Color(102, 102, 102));
        A8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        A8.setForeground(new java.awt.Color(255, 255, 255));
        A8.setText("8");
        jPanel1.add(A8);

        A7.setBackground(new java.awt.Color(102, 102, 102));
        A7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        A7.setForeground(new java.awt.Color(255, 255, 255));
        A7.setText("7");
        jPanel1.add(A7);

        A6.setBackground(new java.awt.Color(102, 102, 102));
        A6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        A6.setForeground(new java.awt.Color(255, 255, 255));
        A6.setText("6");
        jPanel1.add(A6);

        A5.setBackground(new java.awt.Color(102, 102, 102));
        A5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        A5.setForeground(new java.awt.Color(255, 255, 255));
        A5.setText("5");
        jPanel1.add(A5);

        jButton14.setBackground(new java.awt.Color(102, 102, 102));
        jButton14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setText("8");
        jPanel1.add(jButton14);

        jButton7.setBackground(new java.awt.Color(102, 102, 102));
        jButton7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("7");
        jPanel1.add(jButton7);

        jButton8.setBackground(new java.awt.Color(102, 102, 102));
        jButton8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("6");
        jPanel1.add(jButton8);

        jButton9.setBackground(new java.awt.Color(102, 102, 102));
        jButton9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("5");
        jPanel1.add(jButton9);

        jButton25.setBackground(new java.awt.Color(102, 102, 102));
        jButton25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton25.setForeground(new java.awt.Color(255, 255, 255));
        jButton25.setText("8");
        jPanel1.add(jButton25);

        jButton10.setBackground(new java.awt.Color(102, 102, 102));
        jButton10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("7");
        jPanel1.add(jButton10);

        jButton11.setBackground(new java.awt.Color(102, 102, 102));
        jButton11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("6");
        jPanel1.add(jButton11);

        jButton12.setBackground(new java.awt.Color(102, 102, 102));
        jButton12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("5");
        jPanel1.add(jButton12);

        jButton23.setBackground(new java.awt.Color(102, 102, 102));
        jButton23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton23.setForeground(new java.awt.Color(255, 255, 255));
        jButton23.setText("8");
        jPanel1.add(jButton23);

        jButton24.setBackground(new java.awt.Color(102, 102, 102));
        jButton24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton24.setForeground(new java.awt.Color(255, 255, 255));
        jButton24.setText("7");
        jPanel1.add(jButton24);

        jButton13.setBackground(new java.awt.Color(102, 102, 102));
        jButton13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("6");
        jPanel1.add(jButton13);

        jButton15.setBackground(new java.awt.Color(102, 102, 102));
        jButton15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("5");
        jPanel1.add(jButton15);

        jButton16.setBackground(new java.awt.Color(153, 153, 0));
        jButton16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton16.setForeground(new java.awt.Color(255, 255, 255));
        jButton16.setText("8");
        jPanel1.add(jButton16);

        jButton22.setBackground(new java.awt.Color(153, 153, 0));
        jButton22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton22.setForeground(new java.awt.Color(255, 255, 255));
        jButton22.setText("7");
        jPanel1.add(jButton22);

        jButton17.setBackground(new java.awt.Color(153, 153, 0));
        jButton17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton17.setForeground(new java.awt.Color(255, 255, 255));
        jButton17.setText("6");
        jPanel1.add(jButton17);

        jButton18.setBackground(new java.awt.Color(153, 153, 0));
        jButton18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton18.setForeground(new java.awt.Color(255, 255, 255));
        jButton18.setText("5");
        jPanel1.add(jButton18);

        jButton26.setBackground(new java.awt.Color(153, 153, 0));
        jButton26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton26.setForeground(new java.awt.Color(255, 255, 255));
        jButton26.setText("8");
        jPanel1.add(jButton26);

        jButton21.setBackground(new java.awt.Color(153, 153, 0));
        jButton21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton21.setForeground(new java.awt.Color(255, 255, 255));
        jButton21.setText("7");
        jPanel1.add(jButton21);

        jButton19.setBackground(new java.awt.Color(153, 153, 0));
        jButton19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton19.setForeground(new java.awt.Color(255, 255, 255));
        jButton19.setText("6");
        jPanel1.add(jButton19);

        jButton20.setBackground(new java.awt.Color(153, 153, 0));
        jButton20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton20.setForeground(new java.awt.Color(255, 255, 255));
        jButton20.setText("5");
        jPanel1.add(jButton20);

        jButton27.setBackground(new java.awt.Color(153, 153, 0));
        jButton27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton27.setForeground(new java.awt.Color(255, 255, 255));
        jButton27.setText("8");
        jPanel1.add(jButton27);

        jButton28.setBackground(new java.awt.Color(153, 153, 0));
        jButton28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton28.setForeground(new java.awt.Color(255, 255, 255));
        jButton28.setText("7");
        jPanel1.add(jButton28);

        jButton29.setBackground(new java.awt.Color(153, 153, 0));
        jButton29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton29.setForeground(new java.awt.Color(255, 255, 255));
        jButton29.setText("6");
        jPanel1.add(jButton29);

        jButton30.setBackground(new java.awt.Color(153, 153, 0));
        jButton30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton30.setForeground(new java.awt.Color(255, 255, 255));
        jButton30.setText("5");
        jPanel1.add(jButton30);

        jButton31.setBackground(new java.awt.Color(102, 102, 102));
        jButton31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton31.setForeground(new java.awt.Color(255, 255, 255));
        jButton31.setText("8");
        jPanel1.add(jButton31);

        jButton32.setBackground(new java.awt.Color(102, 102, 102));
        jButton32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton32.setForeground(new java.awt.Color(255, 255, 255));
        jButton32.setText("7");
        jPanel1.add(jButton32);

        jButton33.setBackground(new java.awt.Color(102, 102, 102));
        jButton33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton33.setForeground(new java.awt.Color(255, 255, 255));
        jButton33.setText("6");
        jPanel1.add(jButton33);

        jButton37.setBackground(new java.awt.Color(102, 102, 102));
        jButton37.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton37.setForeground(new java.awt.Color(255, 255, 255));
        jButton37.setText("5");
        jPanel1.add(jButton37);

        jButton34.setBackground(new java.awt.Color(102, 102, 102));
        jButton34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton34.setForeground(new java.awt.Color(255, 255, 255));
        jButton34.setText("8");
        jPanel1.add(jButton34);

        jButton40.setBackground(new java.awt.Color(102, 102, 102));
        jButton40.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton40.setForeground(new java.awt.Color(255, 255, 255));
        jButton40.setText("7");
        jPanel1.add(jButton40);

        jButton35.setBackground(new java.awt.Color(102, 102, 102));
        jButton35.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton35.setForeground(new java.awt.Color(255, 255, 255));
        jButton35.setText("6");
        jPanel1.add(jButton35);

        jButton38.setBackground(new java.awt.Color(102, 102, 102));
        jButton38.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton38.setForeground(new java.awt.Color(255, 255, 255));
        jButton38.setText("5");
        jPanel1.add(jButton38);

        jButton36.setBackground(new java.awt.Color(102, 102, 102));
        jButton36.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton36.setForeground(new java.awt.Color(255, 255, 255));
        jButton36.setText("8");
        jPanel1.add(jButton36);

        jButton39.setBackground(new java.awt.Color(102, 102, 102));
        jButton39.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton39.setForeground(new java.awt.Color(255, 255, 255));
        jButton39.setText("7");
        jPanel1.add(jButton39);

        jButton41.setBackground(new java.awt.Color(102, 102, 102));
        jButton41.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton41.setForeground(new java.awt.Color(255, 255, 255));
        jButton41.setText("6");
        jPanel1.add(jButton41);

        jButton42.setBackground(new java.awt.Color(102, 102, 102));
        jButton42.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton42.setForeground(new java.awt.Color(255, 255, 255));
        jButton42.setText("5");
        jPanel1.add(jButton42);

        jButton131.setBackground(new java.awt.Color(204, 0, 204));
        jButton131.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton131.setForeground(new java.awt.Color(255, 255, 255));
        jButton131.setText("8");
        jPanel1.add(jButton131);

        jButton132.setBackground(new java.awt.Color(204, 0, 204));
        jButton132.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton132.setForeground(new java.awt.Color(255, 255, 255));
        jButton132.setText("7");
        jPanel1.add(jButton132);

        jButton133.setBackground(new java.awt.Color(204, 0, 204));
        jButton133.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton133.setForeground(new java.awt.Color(255, 255, 255));
        jButton133.setText("6");
        jPanel1.add(jButton133);

        jButton134.setBackground(new java.awt.Color(204, 0, 204));
        jButton134.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton134.setForeground(new java.awt.Color(255, 255, 255));
        jButton134.setText("5");
        jPanel1.add(jButton134);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 420, 310));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new java.awt.GridLayout(11, 1));

        A.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        A.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A.setText("A");
        A.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(A);

        B.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        B.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B.setText("B");
        B.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(B);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("C");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel4);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("D");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel5);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("E");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel6);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("F");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel7);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("G");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel8);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("H");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel9);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("J");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel10);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("K");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel11);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("L");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel12);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 60, 310));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new java.awt.GridLayout(11, 4));

        A4.setBackground(new java.awt.Color(255, 51, 51));
        A4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        A4.setForeground(new java.awt.Color(255, 82, 8));
        A4.setText("4");
        jPanel3.add(A4);

        A3.setBackground(new java.awt.Color(102, 102, 102));
        A3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        A3.setForeground(new java.awt.Color(255, 255, 255));
        A3.setText("3");
        jPanel3.add(A3);

        A2.setBackground(new java.awt.Color(102, 102, 102));
        A2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        A2.setForeground(new java.awt.Color(255, 255, 255));
        A2.setText("2");
        jPanel3.add(A2);

        A1.setBackground(new java.awt.Color(102, 102, 102));
        A1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        A1.setForeground(new java.awt.Color(255, 255, 255));
        A1.setText("1");
        jPanel3.add(A1);

        jButton47.setBackground(new java.awt.Color(102, 102, 102));
        jButton47.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton47.setForeground(new java.awt.Color(255, 255, 255));
        jButton47.setText("4");
        jPanel3.add(jButton47);

        jButton48.setBackground(new java.awt.Color(102, 102, 102));
        jButton48.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton48.setForeground(new java.awt.Color(255, 255, 255));
        jButton48.setText("3");
        jPanel3.add(jButton48);

        jButton49.setBackground(new java.awt.Color(102, 102, 102));
        jButton49.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton49.setForeground(new java.awt.Color(255, 255, 255));
        jButton49.setText("2");
        jPanel3.add(jButton49);

        jButton50.setBackground(new java.awt.Color(102, 102, 102));
        jButton50.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton50.setForeground(new java.awt.Color(255, 255, 255));
        jButton50.setText("1");
        jPanel3.add(jButton50);

        jButton51.setBackground(new java.awt.Color(102, 102, 102));
        jButton51.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton51.setForeground(new java.awt.Color(255, 255, 255));
        jButton51.setText("4");
        jPanel3.add(jButton51);

        jButton52.setBackground(new java.awt.Color(102, 102, 102));
        jButton52.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton52.setForeground(new java.awt.Color(255, 255, 255));
        jButton52.setText("3");
        jPanel3.add(jButton52);

        jButton53.setBackground(new java.awt.Color(102, 102, 102));
        jButton53.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton53.setForeground(new java.awt.Color(255, 255, 255));
        jButton53.setText("2");
        jPanel3.add(jButton53);

        jButton54.setBackground(new java.awt.Color(102, 102, 102));
        jButton54.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton54.setForeground(new java.awt.Color(255, 255, 255));
        jButton54.setText("1");
        jPanel3.add(jButton54);

        jButton55.setBackground(new java.awt.Color(102, 102, 102));
        jButton55.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton55.setForeground(new java.awt.Color(255, 255, 255));
        jButton55.setText("4");
        jPanel3.add(jButton55);

        jButton56.setBackground(new java.awt.Color(102, 102, 102));
        jButton56.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton56.setForeground(new java.awt.Color(255, 255, 255));
        jButton56.setText("3");
        jPanel3.add(jButton56);

        jButton57.setBackground(new java.awt.Color(102, 102, 102));
        jButton57.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton57.setForeground(new java.awt.Color(255, 255, 255));
        jButton57.setText("2");
        jPanel3.add(jButton57);

        jButton58.setBackground(new java.awt.Color(102, 102, 102));
        jButton58.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton58.setForeground(new java.awt.Color(255, 255, 255));
        jButton58.setText("1");
        jPanel3.add(jButton58);

        jButton59.setBackground(new java.awt.Color(153, 153, 0));
        jButton59.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton59.setForeground(new java.awt.Color(255, 255, 255));
        jButton59.setText("4");
        jPanel3.add(jButton59);

        jButton60.setBackground(new java.awt.Color(153, 153, 0));
        jButton60.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton60.setForeground(new java.awt.Color(255, 255, 255));
        jButton60.setText("3");
        jPanel3.add(jButton60);

        jButton61.setBackground(new java.awt.Color(153, 153, 0));
        jButton61.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton61.setForeground(new java.awt.Color(255, 255, 255));
        jButton61.setText("2");
        jPanel3.add(jButton61);

        jButton62.setBackground(new java.awt.Color(153, 153, 0));
        jButton62.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton62.setForeground(new java.awt.Color(255, 255, 255));
        jButton62.setText("1");
        jPanel3.add(jButton62);

        jButton63.setBackground(new java.awt.Color(153, 153, 0));
        jButton63.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton63.setForeground(new java.awt.Color(255, 255, 255));
        jButton63.setText("4");
        jPanel3.add(jButton63);

        jButton64.setBackground(new java.awt.Color(153, 153, 0));
        jButton64.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton64.setForeground(new java.awt.Color(255, 255, 255));
        jButton64.setText("3");
        jPanel3.add(jButton64);

        jButton65.setBackground(new java.awt.Color(153, 153, 0));
        jButton65.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton65.setForeground(new java.awt.Color(255, 255, 255));
        jButton65.setText("2");
        jPanel3.add(jButton65);

        jButton66.setBackground(new java.awt.Color(153, 153, 0));
        jButton66.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton66.setForeground(new java.awt.Color(255, 255, 255));
        jButton66.setText("1");
        jPanel3.add(jButton66);

        jButton67.setBackground(new java.awt.Color(153, 153, 0));
        jButton67.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton67.setForeground(new java.awt.Color(255, 255, 255));
        jButton67.setText("4");
        jPanel3.add(jButton67);

        jButton68.setBackground(new java.awt.Color(153, 153, 0));
        jButton68.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton68.setForeground(new java.awt.Color(255, 255, 255));
        jButton68.setText("3");
        jPanel3.add(jButton68);

        jButton69.setBackground(new java.awt.Color(153, 153, 0));
        jButton69.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton69.setForeground(new java.awt.Color(255, 255, 255));
        jButton69.setText("2");
        jPanel3.add(jButton69);

        jButton70.setBackground(new java.awt.Color(153, 153, 0));
        jButton70.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton70.setForeground(new java.awt.Color(255, 255, 255));
        jButton70.setText("1");
        jPanel3.add(jButton70);

        jButton71.setBackground(new java.awt.Color(102, 102, 102));
        jButton71.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton71.setForeground(new java.awt.Color(255, 255, 255));
        jButton71.setText("4");
        jPanel3.add(jButton71);

        jButton72.setBackground(new java.awt.Color(102, 102, 102));
        jButton72.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton72.setForeground(new java.awt.Color(255, 255, 255));
        jButton72.setText("3");
        jPanel3.add(jButton72);

        jButton73.setBackground(new java.awt.Color(102, 102, 102));
        jButton73.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton73.setForeground(new java.awt.Color(255, 255, 255));
        jButton73.setText("2");
        jPanel3.add(jButton73);

        jButton74.setBackground(new java.awt.Color(102, 102, 102));
        jButton74.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton74.setForeground(new java.awt.Color(255, 255, 255));
        jButton74.setText("1");
        jPanel3.add(jButton74);

        jButton75.setBackground(new java.awt.Color(102, 102, 102));
        jButton75.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton75.setForeground(new java.awt.Color(255, 255, 255));
        jButton75.setText("4");
        jPanel3.add(jButton75);

        jButton76.setBackground(new java.awt.Color(102, 102, 102));
        jButton76.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton76.setForeground(new java.awt.Color(255, 255, 255));
        jButton76.setText("3");
        jPanel3.add(jButton76);

        jButton77.setBackground(new java.awt.Color(102, 102, 102));
        jButton77.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton77.setForeground(new java.awt.Color(255, 255, 255));
        jButton77.setText("2");
        jPanel3.add(jButton77);

        jButton78.setBackground(new java.awt.Color(102, 102, 102));
        jButton78.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton78.setForeground(new java.awt.Color(255, 255, 255));
        jButton78.setText("1");
        jPanel3.add(jButton78);

        jButton79.setBackground(new java.awt.Color(102, 102, 102));
        jButton79.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton79.setForeground(new java.awt.Color(255, 255, 255));
        jButton79.setText("4");
        jPanel3.add(jButton79);

        jButton80.setBackground(new java.awt.Color(102, 102, 102));
        jButton80.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton80.setForeground(new java.awt.Color(255, 255, 255));
        jButton80.setText("3");
        jPanel3.add(jButton80);

        jButton81.setBackground(new java.awt.Color(102, 102, 102));
        jButton81.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton81.setForeground(new java.awt.Color(255, 255, 255));
        jButton81.setText("2");
        jPanel3.add(jButton81);

        jButton82.setBackground(new java.awt.Color(102, 102, 102));
        jButton82.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton82.setForeground(new java.awt.Color(255, 255, 255));
        jButton82.setText("1");
        jPanel3.add(jButton82);

        jButton83.setBackground(new java.awt.Color(204, 0, 204));
        jButton83.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton83.setForeground(new java.awt.Color(255, 255, 255));
        jButton83.setText("4");
        jPanel3.add(jButton83);

        jButton84.setBackground(new java.awt.Color(204, 0, 204));
        jButton84.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton84.setForeground(new java.awt.Color(255, 255, 255));
        jButton84.setText("3");
        jPanel3.add(jButton84);

        jButton85.setBackground(new java.awt.Color(204, 0, 204));
        jButton85.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton85.setForeground(new java.awt.Color(255, 255, 255));
        jButton85.setText("2");
        jPanel3.add(jButton85);

        jButton86.setBackground(new java.awt.Color(204, 0, 204));
        jButton86.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton86.setForeground(new java.awt.Color(255, 255, 255));
        jButton86.setText("1");
        jPanel3.add(jButton86);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 70, 260, 310));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new java.awt.GridLayout(11, 4));

        A12.setBackground(new java.awt.Color(102, 102, 102));
        A12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        A12.setForeground(new java.awt.Color(255, 255, 255));
        A12.setText("12");
        A12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A12MouseClicked(evt);
            }
        });
        jPanel4.add(A12);

        A11.setBackground(new java.awt.Color(102, 102, 102));
        A11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        A11.setForeground(new java.awt.Color(255, 255, 255));
        A11.setText("11");
        jPanel4.add(A11);

        A10.setBackground(new java.awt.Color(102, 102, 102));
        A10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        A10.setForeground(new java.awt.Color(255, 255, 255));
        A10.setText("10");
        jPanel4.add(A10);

        A9.setBackground(new java.awt.Color(102, 102, 102));
        A9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        A9.setForeground(new java.awt.Color(255, 255, 255));
        A9.setText("9");
        jPanel4.add(A9);

        B12.setBackground(new java.awt.Color(102, 102, 102));
        B12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        B12.setForeground(new java.awt.Color(255, 255, 255));
        B12.setText("12");
        jPanel4.add(B12);

        jButton92.setBackground(new java.awt.Color(102, 102, 102));
        jButton92.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton92.setForeground(new java.awt.Color(255, 255, 255));
        jButton92.setText("11");
        jPanel4.add(jButton92);

        jButton93.setBackground(new java.awt.Color(102, 102, 102));
        jButton93.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton93.setForeground(new java.awt.Color(255, 255, 255));
        jButton93.setText("10");
        jPanel4.add(jButton93);

        jButton94.setBackground(new java.awt.Color(102, 102, 102));
        jButton94.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton94.setForeground(new java.awt.Color(255, 255, 255));
        jButton94.setText("9");
        jPanel4.add(jButton94);

        C12.setBackground(new java.awt.Color(102, 102, 102));
        C12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        C12.setForeground(new java.awt.Color(255, 255, 255));
        C12.setText("12");
        jPanel4.add(C12);

        jButton96.setBackground(new java.awt.Color(102, 102, 102));
        jButton96.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton96.setForeground(new java.awt.Color(255, 255, 255));
        jButton96.setText("11");
        jPanel4.add(jButton96);

        jButton97.setBackground(new java.awt.Color(102, 102, 102));
        jButton97.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton97.setForeground(new java.awt.Color(255, 255, 255));
        jButton97.setText("10");
        jPanel4.add(jButton97);

        jButton98.setBackground(new java.awt.Color(102, 102, 102));
        jButton98.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton98.setForeground(new java.awt.Color(255, 255, 255));
        jButton98.setText("9");
        jPanel4.add(jButton98);

        D12.setBackground(new java.awt.Color(102, 102, 102));
        D12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        D12.setForeground(new java.awt.Color(255, 255, 255));
        D12.setText("12");
        jPanel4.add(D12);

        jButton100.setBackground(new java.awt.Color(102, 102, 102));
        jButton100.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton100.setForeground(new java.awt.Color(255, 255, 255));
        jButton100.setText("11");
        jPanel4.add(jButton100);

        jButton101.setBackground(new java.awt.Color(102, 102, 102));
        jButton101.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton101.setForeground(new java.awt.Color(255, 255, 255));
        jButton101.setText("10");
        jPanel4.add(jButton101);

        jButton102.setBackground(new java.awt.Color(102, 102, 102));
        jButton102.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton102.setForeground(new java.awt.Color(255, 255, 255));
        jButton102.setText("9");
        jPanel4.add(jButton102);

        E12.setBackground(new java.awt.Color(153, 153, 0));
        E12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        E12.setForeground(new java.awt.Color(255, 255, 255));
        E12.setText("12");
        jPanel4.add(E12);

        jButton104.setBackground(new java.awt.Color(153, 153, 0));
        jButton104.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton104.setForeground(new java.awt.Color(255, 255, 255));
        jButton104.setText("11");
        jPanel4.add(jButton104);

        jButton105.setBackground(new java.awt.Color(153, 153, 0));
        jButton105.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton105.setForeground(new java.awt.Color(255, 255, 255));
        jButton105.setText("10");
        jPanel4.add(jButton105);

        jButton106.setBackground(new java.awt.Color(153, 153, 0));
        jButton106.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton106.setForeground(new java.awt.Color(255, 255, 255));
        jButton106.setText("9");
        jPanel4.add(jButton106);

        F12.setBackground(new java.awt.Color(153, 153, 0));
        F12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        F12.setForeground(new java.awt.Color(255, 255, 255));
        F12.setText("12");
        jPanel4.add(F12);

        jButton108.setBackground(new java.awt.Color(153, 153, 0));
        jButton108.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton108.setForeground(new java.awt.Color(255, 255, 255));
        jButton108.setText("11");
        jPanel4.add(jButton108);

        jButton109.setBackground(new java.awt.Color(153, 153, 0));
        jButton109.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton109.setForeground(new java.awt.Color(255, 255, 255));
        jButton109.setText("10");
        jPanel4.add(jButton109);

        jButton110.setBackground(new java.awt.Color(153, 153, 0));
        jButton110.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton110.setForeground(new java.awt.Color(255, 255, 255));
        jButton110.setText("9");
        jPanel4.add(jButton110);

        G12.setBackground(new java.awt.Color(153, 153, 0));
        G12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        G12.setForeground(new java.awt.Color(255, 255, 255));
        G12.setText("12");
        jPanel4.add(G12);

        jButton112.setBackground(new java.awt.Color(153, 153, 0));
        jButton112.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton112.setForeground(new java.awt.Color(255, 255, 255));
        jButton112.setText("11");
        jPanel4.add(jButton112);

        jButton113.setBackground(new java.awt.Color(153, 153, 0));
        jButton113.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton113.setForeground(new java.awt.Color(255, 255, 255));
        jButton113.setText("10");
        jPanel4.add(jButton113);

        jButton114.setBackground(new java.awt.Color(153, 153, 0));
        jButton114.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton114.setForeground(new java.awt.Color(255, 255, 255));
        jButton114.setText("9");
        jPanel4.add(jButton114);

        jButton115.setBackground(new java.awt.Color(102, 102, 102));
        jButton115.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton115.setForeground(new java.awt.Color(255, 255, 255));
        jButton115.setText("12");
        jPanel4.add(jButton115);

        jButton116.setBackground(new java.awt.Color(102, 102, 102));
        jButton116.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton116.setForeground(new java.awt.Color(255, 255, 255));
        jButton116.setText("11");
        jPanel4.add(jButton116);

        jButton117.setBackground(new java.awt.Color(102, 102, 102));
        jButton117.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton117.setForeground(new java.awt.Color(255, 255, 255));
        jButton117.setText("10");
        jPanel4.add(jButton117);

        jButton118.setBackground(new java.awt.Color(102, 102, 102));
        jButton118.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton118.setForeground(new java.awt.Color(255, 255, 255));
        jButton118.setText("9");
        jPanel4.add(jButton118);

        jButton119.setBackground(new java.awt.Color(102, 102, 102));
        jButton119.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton119.setForeground(new java.awt.Color(255, 255, 255));
        jButton119.setText("12");
        jPanel4.add(jButton119);

        jButton120.setBackground(new java.awt.Color(102, 102, 102));
        jButton120.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton120.setForeground(new java.awt.Color(255, 255, 255));
        jButton120.setText("11");
        jPanel4.add(jButton120);

        jButton121.setBackground(new java.awt.Color(102, 102, 102));
        jButton121.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton121.setForeground(new java.awt.Color(255, 255, 255));
        jButton121.setText("10");
        jPanel4.add(jButton121);

        jButton122.setBackground(new java.awt.Color(102, 102, 102));
        jButton122.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton122.setForeground(new java.awt.Color(255, 255, 255));
        jButton122.setText("9");
        jPanel4.add(jButton122);

        jButton123.setBackground(new java.awt.Color(102, 102, 102));
        jButton123.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton123.setForeground(new java.awt.Color(255, 255, 255));
        jButton123.setText("12");
        jPanel4.add(jButton123);

        jButton124.setBackground(new java.awt.Color(102, 102, 102));
        jButton124.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton124.setForeground(new java.awt.Color(255, 255, 255));
        jButton124.setText("11");
        jPanel4.add(jButton124);

        jButton125.setBackground(new java.awt.Color(102, 102, 102));
        jButton125.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton125.setForeground(new java.awt.Color(255, 255, 255));
        jButton125.setText("10");
        jPanel4.add(jButton125);

        jButton126.setBackground(new java.awt.Color(102, 102, 102));
        jButton126.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton126.setForeground(new java.awt.Color(255, 255, 255));
        jButton126.setText("9");
        jPanel4.add(jButton126);

        jButton127.setBackground(new java.awt.Color(204, 0, 204));
        jButton127.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton127.setForeground(new java.awt.Color(255, 255, 255));
        jButton127.setText("12");
        jPanel4.add(jButton127);

        jButton128.setBackground(new java.awt.Color(204, 0, 204));
        jButton128.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton128.setForeground(new java.awt.Color(255, 255, 255));
        jButton128.setText("11");
        jPanel4.add(jButton128);

        jButton129.setBackground(new java.awt.Color(204, 0, 204));
        jButton129.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton129.setForeground(new java.awt.Color(255, 255, 255));
        jButton129.setText("10");
        jPanel4.add(jButton129);

        jButton130.setBackground(new java.awt.Color(204, 0, 204));
        jButton130.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton130.setForeground(new java.awt.Color(255, 255, 255));
        jButton130.setText("9");
        jPanel4.add(jButton130);

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 260, 310));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Ghế đã chọn");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 90, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Ghế Thường");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 90, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Ghế Vip");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 90, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Ghế Couple");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 90, 20));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Ghế chưa chọn");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 110, 20));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/black.png"))); // NOI18N
        jLabel16.setText("jLabel16");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 410, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void A12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A12MouseClicked
        A12.setBackground(new Color(253,253,253));
    }//GEN-LAST:event_A12MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pickghe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pickghe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pickghe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pickghe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pickghe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A;
    private javax.swing.JButton A1;
    private javax.swing.JButton A10;
    private javax.swing.JButton A11;
    private javax.swing.JButton A12;
    private javax.swing.JButton A2;
    private javax.swing.JButton A3;
    private javax.swing.JButton A4;
    private javax.swing.JButton A5;
    private javax.swing.JButton A6;
    private javax.swing.JButton A7;
    private javax.swing.JButton A8;
    private javax.swing.JButton A9;
    private javax.swing.JLabel B;
    private javax.swing.JButton B12;
    private javax.swing.JButton C12;
    private javax.swing.JButton D12;
    private javax.swing.JButton E12;
    private javax.swing.JButton F12;
    private javax.swing.JButton G12;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton100;
    private javax.swing.JButton jButton101;
    private javax.swing.JButton jButton102;
    private javax.swing.JButton jButton104;
    private javax.swing.JButton jButton105;
    private javax.swing.JButton jButton106;
    private javax.swing.JButton jButton108;
    private javax.swing.JButton jButton109;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton110;
    private javax.swing.JButton jButton112;
    private javax.swing.JButton jButton113;
    private javax.swing.JButton jButton114;
    private javax.swing.JButton jButton115;
    private javax.swing.JButton jButton116;
    private javax.swing.JButton jButton117;
    private javax.swing.JButton jButton118;
    private javax.swing.JButton jButton119;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton120;
    private javax.swing.JButton jButton121;
    private javax.swing.JButton jButton122;
    private javax.swing.JButton jButton123;
    private javax.swing.JButton jButton124;
    private javax.swing.JButton jButton125;
    private javax.swing.JButton jButton126;
    private javax.swing.JButton jButton127;
    private javax.swing.JButton jButton128;
    private javax.swing.JButton jButton129;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton130;
    private javax.swing.JButton jButton131;
    private javax.swing.JButton jButton132;
    private javax.swing.JButton jButton133;
    private javax.swing.JButton jButton134;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton68;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButton71;
    private javax.swing.JButton jButton72;
    private javax.swing.JButton jButton73;
    private javax.swing.JButton jButton74;
    private javax.swing.JButton jButton75;
    private javax.swing.JButton jButton76;
    private javax.swing.JButton jButton77;
    private javax.swing.JButton jButton78;
    private javax.swing.JButton jButton79;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton80;
    private javax.swing.JButton jButton81;
    private javax.swing.JButton jButton82;
    private javax.swing.JButton jButton83;
    private javax.swing.JButton jButton84;
    private javax.swing.JButton jButton85;
    private javax.swing.JButton jButton86;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButton92;
    private javax.swing.JButton jButton93;
    private javax.swing.JButton jButton94;
    private javax.swing.JButton jButton96;
    private javax.swing.JButton jButton97;
    private javax.swing.JButton jButton98;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
