/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PhimController;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import model.Phim;
import model.DoanhThu;
import controller.DoanhThuController;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hp
 */
public class QLDoanhThu extends javax.swing.JFrame {
private PhimController phimController;
private DoanhThuController DoanhThuController;
 private DefaultTableModel modelDoanhThu = null;
 private ArrayList<Integer> listmaphim ; 
 private List<Phim> phim;
 private ArrayList<String> tenPhim;

    /**
     * Creates new form QLDoanhThu
     */
    public QLDoanhThu() throws SQLException {
         initComponents();
         tenPhim = new ArrayList<>();
         phimController = new PhimController();
         DoanhThuController= new DoanhThuController();
         listmaphim =new ArrayList<>();
         renderComboBoxChonPhim();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        selectPhim = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        btnXuatdoanhthu = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        selectedNam = new com.toedter.calendar.JYearChooser();
        selectedThang = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbdoanhthu = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 0, 204));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_statistics_40px.png"))); // NOI18N
        jLabel12.setText("THỐNG KÊ DOANH THU ");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 352, 41));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 204));
        jLabel13.setText("Chọn tháng:");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 100, -1));

        selectPhim.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        selectPhim.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selectPhimItemStateChanged(evt);
            }
        });
        selectPhim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectPhimActionPerformed(evt);
            }
        });
        jPanel3.add(selectPhim, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 150, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 204));
        jLabel14.setText("Chọn năm:");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        btnXuatdoanhthu.setBackground(new java.awt.Color(255, 255, 255));
        btnXuatdoanhthu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnXuatdoanhthu.setForeground(new java.awt.Color(0, 204, 102));
        btnXuatdoanhthu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_business_report_40px.png"))); // NOI18N
        btnXuatdoanhthu.setText("Xuất doanh thu");
        btnXuatdoanhthu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatdoanhthuActionPerformed(evt);
            }
        });
        jPanel3.add(btnXuatdoanhthu, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, -1, 45));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 204));
        jLabel15.setText("Tên Phim:");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, -1, -1));
        jPanel3.add(selectedNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 110, 30));

        selectedThang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        selectedThang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jPanel3.add(selectedThang, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 110, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_month_in_love_40px.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 40, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_month_in_love_40px.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 40, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_pixar_lamp_2_40px.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, -1, -1));

        tbdoanhthu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phim", "Tên phim", "Doanh thu"
            }
        ));
        jScrollPane1.setViewportView(tbdoanhthu);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 620, 250));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectPhimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectPhimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectPhimActionPerformed

    private void btnXuatdoanhthuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatdoanhthuActionPerformed
        Integer thang= Integer.parseInt (selectedThang.getSelectedItem().toString());
        int nam =selectedNam.getYear();       
        int maPhim= listmaphim.get(selectPhim.getSelectedIndex());
    try {
        List<DoanhThu> doanhthu = DoanhThuController.layDanhSachDoanhThu(thang, nam, maPhim);
        modelDoanhThu = (DefaultTableModel) tbdoanhthu.getModel();
        modelDoanhThu.setRowCount(0);
        System.out.println("Mã phim da chon: "+maPhim);
         for (DoanhThu dt : doanhthu) {
                Object[] o = new Object[3];
                o[0] = dt.getMaPhim();    
                o[1] = dt.getTenPhim();
                o[2] = dt.getDoanhThu();
                modelDoanhThu.addRow(o);
            }
    } catch (SQLException ex) {
        Logger.getLogger(QLDoanhThu.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnXuatdoanhthuActionPerformed

    private void selectPhimItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selectPhimItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_selectPhimItemStateChanged

    private void renderComboBoxChonPhim() {
        try {
            phim = phimController.layDanhSachPhim();
            for (Phim p : phim) {
                tenPhim.add(p.getMaPhim() + " - " + p.getTenPhim());
                listmaphim.add(p.getMaPhim());
            }
            selectPhim.setModel(new DefaultComboBoxModel(tenPhim.toArray()));
        } catch (SQLException ex) {
            Logger.getLogger(QLDoanhThu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLDoanhThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLDoanhThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLDoanhThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLDoanhThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new QLDoanhThu().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(QLDoanhThu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXuatdoanhthu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> selectPhim;
    private com.toedter.calendar.JYearChooser selectedNam;
    private javax.swing.JComboBox<String> selectedThang;
    private javax.swing.JTable tbdoanhthu;
    // End of variables declaration//GEN-END:variables
}
