/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Helper;
import controller.LoaiNguoiDungController;
import controller.UserController;
import java.net.MalformedURLException;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.LoaiNguoiDung;

/**
 *
 * @author Hp
 */
public class SuaKH extends javax.swing.JFrame {

    private UserController userController;
    private LoaiNguoiDungController loaiNguoiDungController;
    private int taiKhoan;
    private int selectedIndex;
    private ArrayList<String> tenTheLoai;

    public int getTaiKhoan() {
        return taiKhoan;
    }

    public void setTaiKhoan(int taiKhoan) {
        this.taiKhoan = taiKhoan;
    }

    public int getSelectedIndex() {
        return selectedIndex;
    }

    public void setSelectedIndex(int selectedIndex) {
        this.selectedIndex = selectedIndex;
    }

    /**
     * Creates new form TTKH
     */
    public SuaKH() throws SQLException, ClassNotFoundException, ParseException, InterruptedException, MalformedURLException {
        initComponents();
        setTitle("Trang Sửa hoặc xóa Thông Tin User");
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        tenTheLoai = new ArrayList<>();
        userController = new UserController();
        loaiNguoiDungController = new LoaiNguoiDungController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ngaySinhVal = new com.toedter.calendar.JDateChooser();
        tenLoaiVal = new javax.swing.JComboBox<>();
        diemTichLuyVal = new javax.swing.JTextField();
        btxoa = new javax.swing.JButton();
        btBack = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        hoTenVal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btSua = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        diaChiVal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        maKHVal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        soDTVal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Điểm tích lũy");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 100, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ngày sinh");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 90, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Loại:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 77, 30));

        ngaySinhVal.setBackground(new java.awt.Color(204, 204, 204));
        ngaySinhVal.setDateFormatString("dd-MM-yyyy");
        ngaySinhVal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(ngaySinhVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 260, 30));

        tenLoaiVal.setBackground(new java.awt.Color(204, 204, 204));
        tenLoaiVal.setEditable(true);
        tenLoaiVal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tenLoaiVal.setModel(new javax.swing.DefaultComboBoxModel<>());
        tenLoaiVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenLoaiValActionPerformed(evt);
            }
        });
        jPanel1.add(tenLoaiVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 260, 30));

        diemTichLuyVal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        diemTichLuyVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diemTichLuyValActionPerformed(evt);
            }
        });
        jPanel1.add(diemTichLuyVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 260, 30));

        btxoa.setBackground(new java.awt.Color(51, 51, 51));
        btxoa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btxoa.setForeground(new java.awt.Color(51, 255, 51));
        btxoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_minus_32px.png"))); // NOI18N
        btxoa.setText("Xóa");
        btxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxoaActionPerformed(evt);
            }
        });
        jPanel1.add(btxoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, 110, 50));

        btBack.setBackground(new java.awt.Color(51, 51, 51));
        btBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btBack.setForeground(new java.awt.Color(0, 255, 0));
        btBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_back_to_32px_2.png"))); // NOI18N
        btBack.setText("Quay lại");
        btBack.setToolTipText("");
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });
        jPanel1.add(btBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, -1, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("SỬA HOẶC XÓA KHÁCH HÀNG");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 390, 41));

        hoTenVal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        hoTenVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoTenValActionPerformed(evt);
            }
        });
        jPanel1.add(hoTenVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 260, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Họ và tên");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 80, 30));

        btSua.setBackground(new java.awt.Color(51, 51, 51));
        btSua.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btSua.setForeground(new java.awt.Color(52, 255, 51));
        btSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_job_24px_1.png"))); // NOI18N
        btSua.setText("Sửa");
        btSua.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btSuaStateChanged(evt);
            }
        });
        btSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });
        jPanel1.add(btSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 110, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Địa chỉ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 80, 30));

        diaChiVal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        diaChiVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaChiValActionPerformed(evt);
            }
        });
        jPanel1.add(diaChiVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 260, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mã khách hàng");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 120, 30));

        maKHVal.setToolTipText("");
        maKHVal.setEnabled(false);
        jPanel1.add(maKHVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 260, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Số điện thoại");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 100, 30));

        soDTVal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        soDTVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soDTValActionPerformed(evt);
            }
        });
        jPanel1.add(soDTVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 260, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tenLoaiValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenLoaiValActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenLoaiValActionPerformed

    private void diemTichLuyValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diemTichLuyValActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diemTichLuyValActionPerformed

    private void btxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxoaActionPerformed
        // TODO add your handling code here:
        try {
            int result = JOptionPane.showConfirmDialog(SuaKH.this, "Bạn có chắc chắc muốn xóa khách hàng này không?", "Xóa khách hàng",
                    JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                userController.xoaUser(taiKhoan, selectedIndex);
                JOptionPane.showMessageDialog(SuaKH.this, "Xóa khách hàng thành công", "Xóa khách hàng",
                        JOptionPane.INFORMATION_MESSAGE);
                dispose();
            }
        } catch (SQLException ex) {
            Logger.getLogger(SuaKH.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(SuaKH.this, "Xảy ra lỗi khi xóa khách hàng vui lòng chọn khách hàng khác", "Có lỗi",
                    JOptionPane.ERROR_MESSAGE);
            dispose();
        }
    }//GEN-LAST:event_btxoaActionPerformed

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btBackActionPerformed

    private void hoTenValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoTenValActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hoTenValActionPerformed

    private void btSuaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btSuaStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_btSuaStateChanged

    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed
        // TODO add your handling code here:
        int value = tenLoaiVal.getSelectedIndex() + 1;
        java.sql.Date ngSinhVal;
        ngSinhVal = new java.sql.Date(ngaySinhVal.getDate().getTime());
        Object[] o = new Object[6];
        o[0] = hoTenVal.getText();
        o[1] = diaChiVal.getText();
        o[2] = soDTVal.getText();
        o[3] = ngSinhVal;
        o[4] = value;
        o[5] = Integer.parseInt(diemTichLuyVal.getText());
        try {
            userController.suaThongTinUser(taiKhoan, o);
            JOptionPane.showMessageDialog(SuaKH.this, "Sửa thông tin khách hàng thành công", "Thành công",
                    JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(SuaKH.this, "Xảy ra lỗi khi sửa thông tin khách hàng vui lòng chọn khách hàng khác", "Có lỗi",
                    JOptionPane.ERROR_MESSAGE);
            this.setVisible(false);
        }

    }//GEN-LAST:event_btSuaActionPerformed

    private void diaChiValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaChiValActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diaChiValActionPerformed

    private void soDTValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soDTValActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soDTValActionPerformed

    public void renderThongTinUser() throws MalformedURLException {
        try {
            Object[] o = userController.getThongTinUser(taiKhoan);
            maKHVal.setText(o[0].toString());
            hoTenVal.setText((String) o[8]);
            diaChiVal.setText((String) o[5]);
            diemTichLuyVal.setText(o[6].toString());
            soDTVal.setText(o[7].toString());
            ngaySinhVal.setDate((Date) o[4]);
            tenLoaiVal.setSelectedIndex(((int) o[10]) - 1);
            //btSua.setEnabled(false);
            Helper.addChangeListener(hoTenVal, e -> btSua.setEnabled(true));
            Helper.addChangeListener(diaChiVal, e -> btSua.setEnabled(true));
            Helper.addChangeListener(diemTichLuyVal, e -> btSua.setEnabled(true));
            Helper.addChangeListener(soDTVal, e -> btSua.setEnabled(true));
        } catch (SQLException ex) {
            Logger.getLogger(SuaKH.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void renderListLoai() {
        try {
            List<LoaiNguoiDung> lNguoiDung = loaiNguoiDungController.LayDanhSachLoaiNguoiDung();
            for (LoaiNguoiDung lnd : lNguoiDung) {
                tenTheLoai.add(lnd.getTenLoai());
            }
            tenLoaiVal.setModel(new DefaultComboBoxModel<>((String[]) tenTheLoai.toArray(new String[0])));
        } catch (SQLException ex) {
            Logger.getLogger(SuaKH.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuaKH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuaKH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuaKH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuaKH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new SuaKH().setVisible(true);
                    Thread.sleep(5000);

                } catch (SQLException | ClassNotFoundException | ParseException | InterruptedException ex) {
                    Logger.getLogger(QLKH.class.getName()).log(Level.SEVERE, null, ex);
                } catch (MalformedURLException ex) {
                    Logger.getLogger(QLKH.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBack;
    private javax.swing.JButton btSua;
    private javax.swing.JButton btxoa;
    private javax.swing.JTextField diaChiVal;
    private javax.swing.JTextField diemTichLuyVal;
    private javax.swing.JTextField hoTenVal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField maKHVal;
    private com.toedter.calendar.JDateChooser ngaySinhVal;
    private javax.swing.JTextField soDTVal;
    private javax.swing.JComboBox<String> tenLoaiVal;
    // End of variables declaration//GEN-END:variables
}
