/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import controller.Helper;
import controller.PhimController;
import controller.VeController;
import java.net.MalformedURLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import model.Phim;
/**
 *
 * @author Hp
 */
public class XuatHoaDon extends javax.swing.JFrame {
    private VeController veController;
    private int maVe;
    private String tenphim;
    private Date Ngaychieu;
    private Date GioChieu;
    private int selectedIndex;
    private Helper helper;
    /**
     * Creates new form XuatHoaDon
     */
    public int getmaVe() {
        return maVe;
    }

    public void setmaVe(int MaVe) {
        this.maVe = MaVe;
    }
    public String gettenphim() {
        return tenphim;
    }

    public void settenphim(String ten) {
        this.tenphim = ten;
    }
    public Date getNgaychieu() {
        return Ngaychieu;
    }

    public void setNgaychieu(Date ngaychieu) {
        this.Ngaychieu = ngaychieu;
    }
    public Date getGioChieu() {
        return GioChieu;
    }

    public void setGioChieu(Date giochieu) {
        this.GioChieu = giochieu;
    }
    
    public int getSelectedIndex() {
        return selectedIndex;
    }

    public void setSelectedIndex(int selectedIndex) {
        this.selectedIndex = selectedIndex;
    }
    public XuatHoaDon() {
        initComponents();
        setTitle("Trang Xuất Hóa Đơn");
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        veController =new VeController();
       
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        ngaychieutxt = new javax.swing.JTextField();
        giochieutxt = new javax.swing.JTextField();
        giatxt = new javax.swing.JTextField();
        ngaydattxt = new javax.swing.JTextField();
        tenphimtxt = new javax.swing.JTextField();
        mavetxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnXuat = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ngày chiếu");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 130, -1));

        ngaychieutxt.setEditable(false);
        ngaychieutxt.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.add(ngaychieutxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 250, 40));

        giochieutxt.setEditable(false);
        giochieutxt.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.add(giochieutxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 250, 40));

        giatxt.setEditable(false);
        giatxt.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.add(giatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 250, 40));

        ngaydattxt.setEditable(false);
        ngaydattxt.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.add(ngaydattxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 250, 40));

        tenphimtxt.setEditable(false);
        tenphimtxt.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.add(tenphimtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 250, 40));

        mavetxt.setEditable(false);
        mavetxt.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.add(mavetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 250, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Giờ chiếu");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 100, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Giá vé");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 60, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ngày đặt");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 90, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tên phim");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 90, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mã vé");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 60, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Xuất Hóa Đơn");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 460, 40));

        btnXuat.setBackground(new java.awt.Color(255, 255, 255));
        btnXuat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_ok_48px_1.png"))); // NOI18N
        btnXuat.setBorder(null);
        btnXuat.setBorderPainted(false);
        btnXuat.setDefaultCapable(false);
        btnXuat.setOpaque(false);
        btnXuat.setVerifyInputWhenFocusTarget(false);
        btnXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatActionPerformed(evt);
            }
        });
        jPanel1.add(btnXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, -1, -1));

        btnHuy.setBackground(new java.awt.Color(255, 255, 255));
        btnHuy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_cancel_50px.png"))); // NOI18N
        btnHuy.setBorder(null);
        btnHuy.setBorderPainted(false);
        btnHuy.setDefaultCapable(false);
        btnHuy.setOpaque(false);
        btnHuy.setVerifyInputWhenFocusTarget(false);
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });
        jPanel1.add(btnHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatActionPerformed
        // TODO add your handling code here:
        
        int result = JOptionPane.showConfirmDialog(XuatHoaDon.this, "Bạn có chắc chắc muốn xuất hóa đơn không", "Xác nhận xuất hóa đơn",
                JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(XuatHoaDon.this, "Xuất hóa đơn thành công bạn sẽ được chuyển hướng về trang người dùng", "Xuất hóa đơn thành công",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnXuatActionPerformed
public void renderlistVe() throws MalformedURLException {
    SimpleDateFormat DateFormatter = new SimpleDateFormat("dd-MM-yyyy");
        try {
            Object[] o = veController.getThongtinVe(maVe);
            mavetxt.setText(o[0].toString());
            tenphimtxt.setText(tenphim);
            ngaydattxt.setText(DateFormatter.format(o[1]));
            giatxt.setText(o[2].toString());
            ngaychieutxt.setText(DateFormatter.format(Ngaychieu));
            giochieutxt.setText(GioChieu.toString());
           
        } catch (SQLException ex) {
            Logger.getLogger(SuaLichChieu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
       dispose();
        try {
            LichSuDatVe lichsudatve = new LichSuDatVe();
        } catch (SQLException ex) {
            Logger.getLogger(XuatHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }
       LichSuDatVe.main(null);
       
    }//GEN-LAST:event_btnHuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XuatHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XuatHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XuatHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XuatHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XuatHoaDon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnXuat;
    private javax.swing.JTextField giatxt;
    private javax.swing.JTextField giochieutxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mavetxt;
    private javax.swing.JTextField ngaychieutxt;
    private javax.swing.JTextField ngaydattxt;
    private javax.swing.JTextField tenphimtxt;
    // End of variables declaration//GEN-END:variables
}
